apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: shared
spec:
  type: NodePort
  selector:
    app: workhorse
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 30001